name: Build and Test

on:
  push:
    branches:
      - main

jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven Build
        run: mvn clean install

  Testing:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle
